services:
  umrs-api:
    container_name: umrs-api-dev
    image: b216/umrs:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .devcontainer/.env
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    depends_on:
      - keycloak
      
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    depends_on:
      - pgbouncer

  pgbouncer:
    env_file:
      - .devcontainer/.env
    container_name: pgbouncer-dev
    image: pgbouncer/pgbouncer
    ports:
      - "${DB_PORT}:5432"
    environment:
      - DATABASES_USER=${DB_USERNAME}
      - DATABASES_PASSWORD=${DB_PASSWORD}
      - DATABASES_DBNAME=${DB_NAME}
      - DATABASES_HOST=${DB_HOST}
    depends_on:
      - database

  database:
    env_file:
      - .devcontainer/.env
    container_name: database-dev
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD} # superuser password
      - POSTGRES_USER=${DB_USERNAME} # create the specified user with superuser power and a database with the same name if no POSTGRES_DB is specified
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
